services:
  mongo:
    image: mongo:3.6
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - "./shared-mongo:/shared-mongo"
      - mongo-data:/data/db

  app:
    build: .
    container_name: muchwords-app
    ports:
      - "1994:1994"
    depends_on:
      - mongo
    env_file:
      - .docker_env

volumes:
  mongo-data:
